server: 
  port: 8761
eureka: 
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceUrl: 
      defaultZone: http://user:123@peer2:8762/eureka/
  instance: 
    hostname: peer1   
  #dashboard: 
    #path: /webui
spring: 
  application: 
    name: registryservice
  profiles: peer1

security: 
  basic:
    enabled: true
  user: 
    name: user
    password: 123  