server:
  port: 8001
spring:
  application: 
    name: userservice
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate: 
      ddl-auto: none
  datasource: 
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging: 
  level: 
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka: 
  client: 
    serviceUrl:
      defaultZone: http://user:123@peer1:8761/eureka/,http://user:123@peer2:8762/eureka/
  instance: 
    #hostname: userservice-02
    prefer-ip-address: true