server: 
  port: 8762
eureka: 
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceUrl: 
      defaultZone: http://user:123@peer1:8761/eureka/
  instance: 
    hostname: peer2
  #dashboard: 
    #path: /webui
spring: 
  application: 
    name: registryservice-ha
  profiles: peer2
 
security: 
  basic:
    enabled: true
  user: 
    name: user
    password: 123